# Generated by Django 3.2 on 2021-10-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211015_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AddField(
            model_name='cashlink',
            name='type',
            field=models.IntegerField(choices=[(1, 'Если выбрано <неважно> или <до 30>'), (2, 'Если выбрано <неважно> или <до 30>'), (3, 'Если не получилось взять займы')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='cashlink',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cashlink',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.botuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('Key', 'Кнопка'), ('Message', 'Сообщение'), ('Smile', 'Смайл')], max_length=10),
        ),
    ]
