# Generated by Django 3.2 on 2021-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_taskmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ask For Loans 1'), (2, 'Ask For Loans 2')]),
        ),
    ]
